### ISSUE TITLE
Error while compiling: TebexDonate.cs(340,64): error CS1525: Unexpected symbol `end-of-file'

### ISSUE THREAD

**Issue by AmtechInnovarch** [BuycraftPlugin/Tebex-Oxide#15]
I just got this error when I tried to load the plugin you provide in your splash screen for account creation.

Is this plugin compatible with linux based servers or do I need to do a EOF type replace from win to linux?

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
